### ISSUE TITLE
Can you provide the trained model (best_model.pth)?

### ISSUE THREAD

**Issue by lizhyuxi** [Toneyaya/CGFormer#4]
During the evaluation I ran into this problem, and realized that I hadn't downloaded the trained model, because it is not provided.
![image](https://github.com/Toneyaya/CGFormer/assets/71909976/7f4e1214-ee79-43ff-83a7-15eff9478a8b)

Can you provide the trained model? It will help me a lot. Thank you in advance.

**Comment by Toneyaya** [comment]
Sorry for being late. The trained model is now released and you can download it from the link below.
https://huggingface.co/Toneyaya/CGFormer/tree/main
