### ISSUE TITLE
ImportError: cannot import name 'collate_fn' from 'utils.misc'

### ISSUE THREAD

**Issue by lizhyuxi** [Toneyaya/CGFormer#5]
When I try to train the model, it report the following error:
![image](https://github.com/Toneyaya/CGFormer/assets/71909976/348d4cbe-6134-444c-b239-ab88dacd723a)

Then I search in the [CGFormer/utils/misc.py](https://github.com/Toneyaya/CGFormer/blob/main/utils/misc.py), actually I cant find collate_fn function. 
Is there anything wrong? Thank you in advance.

**Comment by Toneyaya** [comment]
Sorry about this missing import error. The following is the specific implementation of collate_fn.

 ``` python 
def collate_fn(batch):  
    batch = list(zip(*batch))
    return tuple(batch)
