### ISSUE TITLE
generalization experiments dataset

### ISSUE THREAD

**Issue by PanXiongAdam** [Toneyaya/CGFormer#7]
Hello Sir.
This is a interest work. 
When will the generalized dataset be publicly available?

Sincerely.

**Comment by Toneyaya** [comment]
Thanks for your interest, the generalization  datasets will be posted this week.

**Comment by PanXiongAdam** [comment]
@Toneyaya Hello, you are forgot to provide the dataset.

**Comment by Toneyaya** [comment]
Sorry, It will be ready in a day. Thank you for reminding me.

**Comment by Toneyaya** [comment]
The dataset files are uploading. You can also follow the tutorial to customize your datasets.
