### ISSUE TITLE
Failed to load train_seen.lmdb in generalization setting

### ISSUE THREAD

**Issue by charon517-517** [Toneyaya/CGFormer#9]
Thanks for your excellent work!  I have some prombles when trying to reproduce the results illustrated in Table 2 of the CGFormer paper.
I follow the [instruction](https://github.com/SooLab/CGFormer/blob/main/data/READEME.md) and download the [open_lmdb.zip](https://drive.google.com/file/d/10qIyrslkX50THzZFgGuompF_tWl5TRW0/view?usp=drive_link) to get the lmdb file. But when I tried to load data from the refcoco/train_seen.lmdb, my process unexpectedly stop when executing this block in `_init_db` function:
```
with self.env.begin(write=False) as txn:
    self.length = loads_pyarrow(txn.get(b'__len__'))
    self.keys = loads_pyarrow(txn.get(b'__keys__'))
```
Moreover, I find that the block mentioned above work fine when I load data from val/test lmdb files, only when I tried to load data from train_***.lmdb, this bug occures. 

Detailed logs are attached to this issue, I would appreciate if you have any idea about how to solve this promble. Thanks again for your excellent work!
[issues.log](https://github.com/user-attachments/files/17974112/issues.log)

**Comment by Toneyaya** [comment]
It’s possible that an error occurred during the file upload. I didn’t experience this issue when using the original files. You can try this link <https://modelscope.cn/datasets/Toneyaya/CGFormer/files>. I’ve re-uploaded a new copy of the open_lmdb. Additionally, please make sure to update the 'info' in the dataset.py under the settings to:

info = {
    'refcoco': {
        'train_seen': 35473,
        'val_seen': 3175,
        'val_unseen': 445,
        'test_seen':3200,
        'test_unseen':394
    },
    'refcoco+': {
        'train_seen': 35375,
        'val_seen': 3171,
        'val_unseen': 444,
        'test_seen':3189,
        'test_unseen':394
    },
    'refcoco_u': {
        'train_seen': 33093,
        'val_seen': 2000,
        'val_unseen': 386,
        'test_seen': 3935,
        'test_unseen': 759,
    },
    'refcoco_g': {
        'train_seen': 35105,
        'val_seen': 3923,
        'val_unseen': 760
    }
}
